deployment:
  tasks:
    - 'export DEPLOYPATH=$HOME/public_html/'
    - '/bin/mkdir -p $DEPLOYPATH'
    - 'npm install'
    - 'npm run build'
    - '/usr/bin/find $DEPLOYPATH -mindepth 1 -maxdepth 1 ! -name .well-known -exec /bin/rm -rf {} +'
    - '/bin/cp -R dist/. $DEPLOYPATH'  # ✅ pastikan folder build adalah 'dist'
